blank_issues_enabled: false
contact_links:
  - name: discord community
    url: https://discord.gg/pQPt8HBUPu
    about: |
      ask questions and discuss cobalt with others at any time.
      usually faster responses as more people are there to help.